FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY worker-bot/pyproject.toml .
RUN uv pip install --system --no-cache -e . alembic

COPY worker-bot/ .
COPY migrations/ migrations/
COPY alembic.ini .

CMD ["alembic", "upgrade", "head"]
